### ISSUE TITLE
substringUnicode and removeUnicode methods

### ISSUE THREAD

**Issue by Voha888** [GyverLibs/StringUtils#5]
Hello! I want to try **Fastbot2**, but I just don’t have the time. I really liked your idea of ​​making a library for text. I also created utilities for text, as an add-on to the standard String class.
I noticed (but I may be wrong, please correct me if this is not so) that you do not have an implementation of the methods **myString.substring(from, to)** for Unicode and **myString.remove(index)/myString.remove(index, count)** for Unicode . If you want, I can add from my libraries?
Perhaps my methods will not be as beautiful and elegant as your implementations, but they work :)

**Comment by GyverLibs** [comment]
mm, yes its good idea!

**Comment by GyverLibs** [comment]
done yeah
